export const ASSETS = {
  images: {
    PLACEHOLDER_IMAGE: require("./assets/background-image.png"),
  },
  emojis: {
    faces: {
      drooling_face: require("./assets/emojis/humans/drooling_face.png"),
      heart_eyes: require("./assets/emojis/humans/heart_eyes.png"),
      grinning: require("./assets/emojis/humans/grinning.png"),
      sunglasses: require("./assets/emojis/humans/sunglasses.png"),
      clown_face: require("./assets/emojis/humans/clown_face.png"),
      confused: require("./assets/emojis/humans/confused.png"),
      kissing_heart: require("./assets/emojis/humans/kissing_heart.png"),
      open_mouth: require("./assets/emojis/humans/open_mouth.png"),
      smiling_imp: require("./assets/emojis/humans/smiling_imp.png"),
      stuck_out_tongue: require("./assets/emojis/humans/stuck_out_tongue.png"),
      tired_face: require("./assets/emojis/humans/tired_face.png"),
      joy: require("./assets/emojis/other/joy.png"),
    },
    other: {
      "100": require("./assets/emojis/other/100.png"),
      moyai: require("./assets/emojis/other/moyai.png"),
      peach: require("./assets/emojis/other/peach.png"),
      soccer: require("./assets/emojis/other/soccer.png"),
      trident: require("./assets/emojis/other/trident.png"),
      bangbang: require("./assets/emojis/other/bangbang.png"),
      basketball: require("./assets/emojis/other/basketball.png"),
      full_moon: require("./assets/emojis/other/full_moon.png"),
      heavy_dollar_sign: require("./assets/emojis/other/heavy_dollar_sign.png"),
      snowflake: require("./assets/emojis/other/snowflake.png"),
      toilet: require("./assets/emojis/other/toilet.png"),
      zap: require("./assets/emojis/other/zap.png"),
    },
    animals: {
      cat2: require("./assets/emojis/animals/cat2.png"),
      chicken: require("./assets/emojis/animals/chicken.png"),
      dog: require("./assets/emojis/animals/dog.png"),
      goat: require("./assets/emojis/animals/goat.png"),
      hatching_chick: require("./assets/emojis/animals/hatching_chick.png"),
      lion_face: require("./assets/emojis/animals/lion_face.png"),
      mouse2: require("./assets/emojis/animals/mouse2.png"),
      turkey: require("./assets/emojis/animals/turkey.png"),
    },
  },
};
